name: Backend CI/CD

on:

  pull_request_review:
    branches: [main]
    types: [submitted]

jobs:
  build:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    env:
      MYSQL_USER: ${{ secrets.MYSQL_USER_1 }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_DATABASE: $ {{ secrets.MYSQL_DATABASE }}
    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Compose
      run: docker-compose -f docker-compose.yml up --build -d
