name: Backend CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MYSQL_USER: ${{ secrets.MYSQL_USER_1 }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_DATABASE: $ {{ secrets.MYSQL_DATABASE }}
    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Compose
      run: docker-compose -f docker-compose.yml up --build -d
